# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin Jeffress
email: justin.jeffress@gmail.com
description: I love to tinker with software and share my knowledge with others in the pursuit enriching people's lives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sleepydeveloper.github.io" # the base hostname & protocol for your site
x_username: sleepydeveloper
github_username:  sleepydeveloper

# Build settings
markdown: kramdown
